owner: Praveen-2328
repo: upptime-bot

sites:
  - name: LabsZone Website
    url: https://labszone.space

  - name: LabsZone Automation (n8n)
    url: https://n8n.labszone.space/healthz

status-website:
  name: LabsZone Status
  introTitle: "⚡ LabsZone System Status"
  introMessage: >
    Real-time uptime and performance monitoring for LabsZone infrastructure & services.

  cname: status.labszone.space
  theme: dark

  logoUrl: https://labszone.space/assets/labszone-icon.svg
  customCss: /custom.css
  customJs: /custom.js

  navbar:
    - title: Status
      href: /
    - title: LabsZone
      href: https://labszone.space
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
