owner: Praveen-2328
repo: upptime-bot

sites:
  - name: LabsZone
    url: https://labszone.space

  - name: LabsZone n8n
    url: https://n8n.labszone.space

status-website:
  name: Praveen Status
  introTitle: "🚀 Service Status"
  introMessage: Monitoring my infrastructure uptime
  baseUrl: /upptime-bot

  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
