owner: Praveen-2328
repo: upptime-bot

sites:
  - name: LabsZone
    url: https://labszone.space

  - name: LabsZone n8n
    url: https://n8n.labszone.space/healthz

status-website:
  name: LabsZone Status
  introTitle: "🚀 LabsZone Service Status"
  introMessage: Monitoring LabsZone infrastructure uptime

  cname: status.labszone.space

  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg

  navbar:
    - title: Status
      href: https://status.labszone.space
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
